"""
This file is the test case for the API.
"""
import json
from django.test import TestCase

import logging
log = logging.getLogger(__name__)
from evaluation import CanvasPolygon,CanvasPolygonSimilarity

class Evaluation(TestCase):
    def setUp(self):
        self.judgement_data1 = {
        u'_shapes': u'{"objects":[{"type":"image","originX":"left","originY":"top","left":0,"top":0,"width":1250,"height":704,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","src":"http://www.ucarecdn.com/92918193-322a-4f05-8935-abba458bb588/-/resize/600x/","filters":[],"crossOrigin":""},{"type":"polygon","originX":"left","originY":"top","left":379,"top":218,"width":1,"height":1,"fill":"green","stroke":"blue","strokeWidth":5,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":0.5,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","points":[{"x":-0.5,"y":-0.5},{"x":253,"y":-60},{"x":406,"y":96},{"x":172,"y":159},{"x":114,"y":477}]}],"background":""}'}
        self.judgement_data2 = {
        u'_shapes': u'{"objects":[{"type":"image","originX":"left","originY":"top","left":0,"top":0,"width":1250,"height":704,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","src":"http://www.ucarecdn.com/92918193-322a-4f05-8935-abba458bb588/-/resize/600x/","filters":[],"crossOrigin":""},{"type":"polygon","originX":"left","originY":"top","left":360,"top":137,"width":1,"height":1,"fill":"green","stroke":"blue","strokeWidth":5,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":0.5,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","points":[{"x":-0.5,"y":-0.5},{"x":73,"y":-73},{"x":274,"y":-85},{"x":618,"y":-29},{"x":623,"y":-15},{"x":584,"y":277},{"x":275,"y":468},{"x":235,"y":465},{"x":209,"y":453},{"x":19,"y":361},{"x":9,"y":335},{"x":-3,"y":128}]}],"background":""}'}
        self.judgement_data3 = {
        u'_shapes': u'{"objects":[{"type":"image","originX":"left","originY":"top","left":0,"top":0,"width":1250,"height":704,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","src":"http://www.ucarecdn.com/92918193-322a-4f05-8935-abba458bb588/-/resize/600x/","filters":[],"crossOrigin":""},{"type":"polygon","originX":"left","originY":"top","left":342,"top":143,"width":1,"height":1,"fill":"green","stroke":"blue","strokeWidth":5,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":0.5,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","points":[{"x":-0.5,"y":-0.5},{"x":86,"y":-85},{"x":297,"y":-100},{"x":655,"y":-41},{"x":619,"y":291},{"x":299,"y":486},{"x":-10,"y":336}]}],"background":""}'}
        self.judgement_data4 = {
        u'_shapes': u'{"objects":[{"type":"image","originX":"left","originY":"top","left":0,"top":0,"width":1250,"height":704,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","src":"http://www.ucarecdn.com/92918193-322a-4f05-8935-abba458bb588/-/resize/600x/","filters":[],"crossOrigin":""},{"type":"polygon","originX":"left","originY":"top","left":360,"top":137,"width":1,"height":1,"fill":"green","stroke":"blue","strokeWidth":5,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":0.5,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","points":[{"x":-0.5,"y":-0.5},{"x":73,"y":-73},{"x":274,"y":-85},{"x":618,"y":-29},{"x":623,"y":-15},{"x":584,"y":277},{"x":275,"y":468},{"x":235,"y":465},{"x":209,"y":453},{"x":19,"y":361},{"x":9,"y":335},{"x":-3,"y":128}]}],"background":""}'}
        self.judgement_data5 = {"_shapes": "{\"objects\":[{\"type\":\"image\",\"originX\":\"left\",\"originY\":\"top\",\"left\":0,\"top\":0,\"width\":370,\"height\":495,\"fill\":\"rgb(0,0,0)\",\"stroke\":null,\"strokeWidth\":1,\"strokeDashArray\":null,\"strokeLineCap\":\"butt\",\"strokeLineJoin\":\"miter\",\"strokeMiterLimit\":10,\"scaleX\":1,\"scaleY\":1,\"angle\":0,\"flipX\":false,\"flipY\":false,\"opacity\":1,\"shadow\":null,\"visible\":true,\"clipTo\":null,\"backgroundColor\":\"\",\"src\":\"http://rockpearl.crowdcafe.io:443/webhook/thumbnail/15063198/?path=/test%20only/inprocess_CCunitid769_pablo_cup%20.jpg\",\"filters\":[],\"crossOrigin\":\"\"},{\"type\":\"polygon\",\"originX\":\"left\",\"originY\":\"top\",\"left\":37,\"top\":175,\"width\":1,\"height\":1,\"fill\":\"green\",\"stroke\":\"blue\",\"strokeWidth\":5,\"strokeDashArray\":null,\"strokeLineCap\":\"butt\",\"strokeLineJoin\":\"miter\",\"strokeMiterLimit\":10,\"scaleX\":1,\"scaleY\":1,\"angle\":0,\"flipX\":false,\"flipY\":false,\"opacity\":0.5,\"shadow\":null,\"visible\":true,\"clipTo\":null,\"backgroundColor\":\"\",\"points\":[{\"x\":-0.5,\"y\":-0.5},{\"x\":0.5,\"y\":-0.5},{\"x\":6,\"y\":11},{\"x\":43,\"y\":26},{\"x\":113,\"y\":38},{\"x\":214,\"y\":40},{\"x\":266,\"y\":28},{\"x\":268,\"y\":16},{\"x\":284,\"y\":24},{\"x\":239,\"y\":215},{\"x\":212,\"y\":231},{\"x\":152,\"y\":252},{\"x\":106,\"y\":252},{\"x\":61,\"y\":240},{\"x\":37,\"y\":222},{\"x\":20,\"y\":196}]}],\"background\":\"\"}"}
        self.judgement_data6 = {"_shapes": "{\"objects\":[{\"type\":\"image\",\"originX\":\"left\",\"originY\":\"top\",\"left\":0,\"top\":0,\"width\":1046,\"height\":1396,\"fill\":\"rgb(0,0,0)\",\"stroke\":null,\"strokeWidth\":1,\"strokeDashArray\":null,\"strokeLineCap\":\"butt\",\"strokeLineJoin\":\"miter\",\"strokeMiterLimit\":10,\"scaleX\":1,\"scaleY\":1,\"angle\":0,\"flipX\":false,\"flipY\":false,\"opacity\":1,\"shadow\":null,\"visible\":true,\"clipTo\":null,\"backgroundColor\":\"\",\"src\":\"http://rockpearl.crowdcafe.io:443/webhook/thumbnail/15063198/?path=/test%20only/inprocess_CCunitid769_pablo_cup%20.jpg\",\"filters\":[],\"crossOrigin\":\"\"},{\"type\":\"polygon\",\"originX\":\"left\",\"originY\":\"top\",\"left\":117,\"top\":496,\"width\":1,\"height\":1,\"fill\":\"green\",\"stroke\":\"blue\",\"strokeWidth\":5,\"strokeDashArray\":null,\"strokeLineCap\":\"butt\",\"strokeLineJoin\":\"miter\",\"strokeMiterLimit\":10,\"scaleX\":1,\"scaleY\":1,\"angle\":0,\"flipX\":false,\"flipY\":false,\"opacity\":0.5,\"shadow\":null,\"visible\":true,\"clipTo\":null,\"backgroundColor\":\"\",\"points\":[{\"x\":-0.5,\"y\":-0.5},{\"x\":0.5,\"y\":-0.5},{\"x\":7,\"y\":31},{\"x\":84,\"y\":69},{\"x\":247,\"y\":103},{\"x\":401,\"y\":120},{\"x\":576,\"y\":114},{\"x\":679,\"y\":99},{\"x\":745,\"y\":80},{\"x\":756,\"y\":43},{\"x\":801,\"y\":66},{\"x\":674,\"y\":595},{\"x\":651,\"y\":624},{\"x\":492,\"y\":701},{\"x\":340,\"y\":721},{\"x\":146,\"y\":667},{\"x\":87,\"y\":614},{\"x\":55,\"y\":564},{\"x\":-7,\"y\":57}]}],\"background\":\"\"}"}
    def not_similar(self):
        cp1 = CanvasPolygon(self.judgement_data1)
        cp2 = CanvasPolygon(self.judgement_data2)
        test = CanvasPolygonSimilarity([cp1,cp2])

        self.assertEqual(test.areSimilar(), False)
    def similar(self):
        cp1 = CanvasPolygon(self.judgement_data3)
        cp2 = CanvasPolygon(self.judgement_data4)
        test = CanvasPolygonSimilarity([cp1,cp2])

        self.assertEqual(test.areSimilar(), True)

    def test_real(self):
        cp1 = CanvasPolygon(self.judgement_data5)
        cp2 = CanvasPolygon(self.judgement_data6)
        test = CanvasPolygonSimilarity([cp1,cp2])

        self.assertEqual(test.areSimilar(), False)